### ISSUE TITLE
Match the color of the input field . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#102]
![image](https://user-images.githubusercontent.com/58114914/156108178-7300ffa2-e4d7-4d87-aae7-04a3b0bb2f04.png)

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by SaraswatGit** [comment]
@03amir  assigned

**Comment by Shruti025** [comment]
I want to work on this under JWOC
