### ISSUE TITLE
Updating contributing section in Readme

### ISSUE THREAD

**Issue by Tess-Vanta** [SaraswatGit/PlanZap#109]
## The current readme have to be updated for Contributing section.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/72697074/156126495-ae8f0ffa-8e47-4011-a048-864d9979c561.png">

### Since the folder structure has been changed, update the setup guidelines to run the project on local

**Comment by Shikhar253** [comment]
Hey, can you assign me this issue?

**Comment by Tess-Vanta** [comment]
Assigned!! If you have any doubt reach us out on discord!
