### ISSUE TITLE
Hovering over logout cursor should change to pointer

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#11]
When the cursor hovers over the logout section it modifies itself to think it as a text element but it should be a pointer . 
![image](https://user-images.githubusercontent.com/58114914/151961727-0e16f482-09d9-4d0d-9a61-d6669a831f63.png)

**Comment by thatsuman** [comment]
Hi, 
I would like to work on this under JWOC

**Comment by reshabh27** [comment]
Hii, I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@reshabh27  I have assigned the issue to you , Best Wishes , for any problems reach out to me on discord .
