### ISSUE TITLE
Issue in adding task

### ISSUE THREAD

**Issue by Shikhar253** [SaraswatGit/PlanZap#110]
when we add a task, it works fine, but then when we click on submit task without even filling any data , it automatically adds a new task with the data of the previous task .

**Comment by SaraswatGit** [comment]
@Shikhar253  I have assigned the issue to you , for any problem reach out to us on discord .

**Comment by Shikhar253** [comment]
Uploading Planzap - Google Chrome 2022-03-01 13-03-12.mp4…

**Comment by Shikhar253** [comment]
> @Shikhar253 I have assigned the issue to you , for any problem reach out to us on discord .

Hey I can't access your channel on discord. I just can't see it anymore

**Comment by SaraswatGit** [comment]
@Shikhar253  it was made private , you can access after opening ceremony after getting self roles .
