### ISSUE TITLE
Adding validation for entering movie details

### ISSUE THREAD

**Issue by Shikhar253** [SaraswatGit/PlanZap#113]
![image](https://user-images.githubusercontent.com/55344241/156130416-8c8c6ac1-6544-416c-b0a8-412a7d9a3e8e.png)

**Comment by Shikhar253** [comment]
Agenda: Prevent submitting empty field

**Comment by NPriyajit** [comment]
I want to work on this

**Comment by SaraswatGit** [comment]
@Shikhar253  Assigned the issue to you , for any problems reach out to us on discord .
