### ISSUE TITLE
Delete tasks is not working properly

### ISSUE THREAD

**Issue by Shikhar253** [SaraswatGit/PlanZap#125]
Whenever we try to delete the task, the one at the end always gets deleted rather than the one which we have clicked

**Comment by Shikhar253** [comment]
Kindly assign me this issue

**Comment by Shikhar253** [comment]
https://user-images.githubusercontent.com/55344241/156227651-c228fb21-349b-4076-9b8c-4b0f43b35982.mp4

**Comment by SaraswatGit** [comment]
@Shikhar253  Assigned the issue to you , for any issues reach out to use on discord .

**Comment by LakshayN** [comment]
@SaraswatGit Can you assign this to me ?

**Comment by SaraswatGit** [comment]
@LakshayN  What;s the status ?

**Comment by LakshayN** [comment]
@SaraswatGit Will try to finish this by tomorrow

**Comment by SaraswatGit** [comment]
@KushalGhosh9899  Assigned , Best wishes for any problem reach out to us on discord .
