### ISSUE TITLE
Cursor should become pointer when hovering over text elements in bottom part of the tasks and progress  page 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#13]
![image](https://user-images.githubusercontent.com/58114914/151981384-307fce37-ac0d-44cc-a94b-a26b81f193e4.png)

**Comment by AnandSY** [comment]
"I want to work on this issue under JWOC"

**Comment by SaraswatGit** [comment]
@AnandSY  I have assigned the issues to you , Best Wishes , For any problems ping me on discord .
