### ISSUE TITLE
Add a circular  loader in the tasklist page  till the tasks have not been fetched

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#139]
A circular loader will run till the api fetch call to get task lists get the data . 

Hint : You can use useState and set its value to false in side .then()

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by SaraswatGit** [comment]
@03amir  i have assigned the issue to you ,just add a circular loader from material UI which will stop showing when the data is fetched .
