### ISSUE TITLE
Change the name of router path of Tasks and Progress page from /Calendar to /TasksandProgress 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#14]
https://planzap.netlify.app/Calendar This link takes you the tasks and progress page make sure you change it .

**Comment by thatsuman** [comment]
Hi,
I would like to work on this under JWOC

**Comment by SaraswatGit** [comment]
> Hi, I would like to work on this under JWOC

Hi @thatsuman  the issue has been assigned to you. Best Wishes.
