### ISSUE TITLE
Change the CSS of Add New task and sort task buttons .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#140]
![image](https://user-images.githubusercontent.com/58114914/156420494-c4f0ae5b-f4fe-488b-9b26-1b430ac81db2.png)
Do the following : 
1)Remove the underline on hover .
2)Change the border radius to make the button have more uniform circular borders in corner . 
3)On hover color should not be blue but a darker or lighter version of current color

**Comment by ashutoshnautiyal7** [comment]
I would like to work on this under GSSoC'22.

**Comment by SaraswatGit** [comment]
@ashutoshnautiyal7 Assigned , for any issues reach out to us on discord .

**Comment by abhiimali** [comment]
if assigned member failed to do it . I would like to work on this under GSSoC'22.

**Comment by SaraswatGit** [comment]
@ashutoshnautiyal7  what's the status ? should i assign it to someone else or you need some more time ?

**Comment by ashutoshnautiyal7** [comment]
I would like to give it a  one more try. Will inform you by tomorrow.

**Comment by ashutoshnautiyal7** [comment]
@SaraswatGit  Completed the task. Please checkout PR.
