### ISSUE TITLE
The cross is not aligned properly  in Add new task modal 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#141]
![image](https://user-images.githubusercontent.com/58114914/156422365-3b1c85a4-1118-4310-99dc-0eea53f9095e.png)
The cross is not aligned properly.

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by SaraswatGit** [comment]
@03amir  Assigned !

**Comment by Shruti025** [comment]
I want to work on this under JWOC
