### ISSUE TITLE
Sort Modal has no cross to close the Modal

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#142]
![image](https://user-images.githubusercontent.com/58114914/156422844-c633bc9d-0400-4524-a376-cd7cb21bcd43.png)

**Comment by 03amir** [comment]
I would like to work on this under GSSoC'22.

**Comment by arzitmahajan** [comment]
I want to  work on this

**Comment by HarshKumarChoudary** [comment]
Please assign it to me. I'm participating in GSSOC 22

**Comment by Tess-Vanta** [comment]
> I want to work on this

Are you under GSSOC 22?
