### ISSUE TITLE
Alignment is not proper  in sort task modal.

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#143]
![image](https://user-images.githubusercontent.com/58114914/156423077-a2d430af-20c8-4529-a6dc-d0b0bb746592.png)
You can see the progress is not aligned properly.

**Comment by ashutoshnautiyal7** [comment]
Please assign this task to me. I would like to work on this under GSSoC'22.

**Comment by SaraswatGit** [comment]
@ashutoshnautiyal7  Assigned , for any issues reach out to us on discord .

**Comment by ashutoshnautiyal7** [comment]
@SaraswatGit  Can you tell me what's the issue?

**Comment by SaraswatGit** [comment]
can u show a screenshot of your file structure with Frontend and Backend folder open .

**Comment by ashutoshnautiyal7** [comment]
attached the screenshot.

**Comment by SaraswatGit** [comment]
@ashutoshnautiyal7  i can't see it

**Comment by ashutoshnautiyal7** [comment]
Check it in your mail.

**Comment by ashutoshnautiyal7** [comment]
Sorry, I am not able to complete this task.

**Comment by mdabdulshahed** [comment]
I want to work on this issue

**Comment by SaraswatGit** [comment]
@mdabdulshahed  Assugned for any issues reach out to us on discord .
