### ISSUE TITLE
Input type in the text description should be textarea

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#144]
![image](https://user-images.githubusercontent.com/58114914/156423621-da3b52cc-902b-4871-802e-a3275e5d7532.png)
As you can see the current input type seems to be text hence we cannot add new line .

**Comment by r3yc0n1c** [comment]
I want to work on this under JWoC'22

**Comment by SaraswatGit** [comment]
@r3yc0n1c  Assigned the issue to you , for any problem reach out to us on discord .
