### ISSUE TITLE
Notes and desciption should have circular borders. 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#145]
![image](https://user-images.githubusercontent.com/58114914/156423902-9c7b34c7-ea5e-4e9b-9335-2f78f02dc6d2.png)
Currently it has square border but circular border would look better.

**Comment by r3yc0n1c** [comment]
I want to work on this under JWoC'22

**Comment by SaraswatGit** [comment]
@r3yc0n1c  Assigned the issue to you , for any problem reach out to us on discord .
