### ISSUE TITLE
Padding needed

### ISSUE THREAD

**Issue by shrutiverma13** [SaraswatGit/PlanZap#148]
![Screenshot (4)](https://user-images.githubusercontent.com/74809049/156540501-b926b0bf-2000-4a5a-877c-6d550bbd3dcd.png)
On the login page, there is padding bottom needed, along with that I believe if the whole website has a general theme, and not include multiple colors, that will enhance the UI on the site a lot.

Please assign the issue of padding to me under Gssoc'22.

**Comment by Tess-Vanta** [comment]
Regarding the theme, you could create a new issue and ill assign it to you. For any further queries you can contact us on the discord channel

**Comment by jyotivakare33** [comment]
@shrutiverma13 Are you still working on it?
@Tess-Vanta Please assign the issue if it is still up for grabs

**Comment by shrutiverma13** [comment]
> @shrutiverma13 Are you still working on it? @Tess-Vanta Please assign the issue if it is still up for grabs

I am working on it.

**Comment by jyotivakare33** [comment]
@Tess-Vanta Is it still open i can close this issue quickly. Can you assign me this issue
