### ISSUE TITLE
On Adding a diary entry or updating it , it should show up on the screen.

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#15]
If you have checked out the diary page . You must have noticed once user puts and new entry or updates a entry , the new /updated entry  doesn't automatically appear . User has to select the date and click on view to see his entry . This should be replaced by whenever the user submits a new entry it should appear below the date selection region,

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
I have assigned the issue to you , Best  Wishes , for any problem reach out to me on discord .
