### ISSUE TITLE
Size of text-area during editing note descri[tion should not reduce 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#164]
![image](https://user-images.githubusercontent.com/58114914/156635731-fdd602f2-2b8d-40f2-8b53-7cc259464b3a.png)

The size of the text-area (when editing reduces) but it should match the size of text present in it . 
![image](https://user-images.githubusercontent.com/58114914/156635766-fd447b47-e093-4ea3-a169-94ff3d2064ff.png)

**Comment by nitishsaini706** [comment]
@SaraswatGit I would like to work on this

**Comment by SaraswatGit** [comment]
@nitishsaini706  I have assigned the issue to you , for any problem reach out to me on discord .
