### ISSUE TITLE
Display a Pop-Up to confirm Deletion of a Task

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#18]
You must have observed when deleting a task just clicking on the cross button deletes it. I want you to display a pop-up to confirm the deletion.
Message can be "Are you sure you want to delete the task".
Earlier: 
Click on Cross -> Task Deleted 
How it should be ?
Click on Cross -> Modal Pops Up -> Confirm ? Task Deleted : Modal Closes .

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC
