### ISSUE TITLE
Movies to Watch DashBoard

### ISSUE THREAD

**Issue by Utkarshking** [SaraswatGit/PlanZap#188]
when we add the movies to watch in the dashboard it appends the dashboard section but we can click on the name of the movie the link should be clickable 
![pic2](https://user-images.githubusercontent.com/61401484/156921617-d8c44835-67fd-4f24-b4a8-ecb94dc4a797.jpg)

**Comment by SaraswatGit** [comment]
@Utkarshking  Assigned , @Tess-Vanta  Will be your  mentor for this issue

**Comment by Tess-Vanta** [comment]
> when we add the movies to watch in the dashboard it appends the dashboard section but we can click on the name of the movie the link should be clickable ![pic2](https://user-images.githubusercontent.com/61401484/156921617-d8c44835-67fd-4f24-b4a8-ecb94dc4a797.jpg)

You want to add link to the movie ?

**Comment by Utkarshking** [comment]
yes

**Comment by Tess-Vanta** [comment]
> yes

Could you explain how so ?

**Comment by Utkarshking** [comment]
i already created a pull request you can check so

**Comment by Tess-Vanta** [comment]
> i already created a pull request you can check so 
> 

Please provide a video of what your code does

**Comment by Utkarshking** [comment]
https://user-images.githubusercontent.com/61401484/158026256-4639f95f-8943-40e8-8b6a-6197e7bed4df.mp4

**Comment by Tess-Vanta** [comment]
> 
> https://user-images.githubusercontent.com/61401484/158026256-4639f95f-8943-40e8-8b6a-6197e7bed4df.mp4
> 
> 

Does it not go on click ? Is it dynamic on entering new data ?

**Comment by Utkarshking** [comment]
NO IT DOES

**Comment by Utkarshking** [comment]
YES IT IS DYANMIC

**Comment by Tess-Vanta** [comment]
Okay I'll merge it

**Comment by Utkarshking** [comment]
THANKU MA'AM
