### ISSUE TITLE
Password and Confirm Password doesn't have the ability to check if they are same 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#2]
If the confirm password and password doesn't match it should show "Password" doesn't match .  There are multiple npm packages which you can use to implement this feature .

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
> I want to work on this issue under JWOC

I have assigned the issue to you best wishes for any doubts ping me on Discord!

**Comment by SaraswatGit** [comment]
> I want to work on this issue under JWOC

I have assigned the issue to you best wishes for any doubts ping me on Discord!

**Comment by raxvab** [comment]
I want to work on this issue under JWOC
