### ISSUE TITLE
Automatically add movie IMDb Rating and Description when adding a movie.

### ISSUE THREAD

**Issue by vakshit** [SaraswatGit/PlanZap#203]
Automatically add a movie's IMDb rating and description. The boxes will be autofilled and can be changed if user wants to.

**Comment by Tess-Vanta** [comment]
You mean default values for the unfilled fields ?

**Comment by vakshit** [comment]
Yup.. i plan to add the IMDb api.. for filling up the rating and description of the movie.

**Comment by Tess-Vanta** [comment]
Go ahead! If you have any doubt feel free to contact us on the discord server.
