### ISSUE TITLE
Index in Readme with link to subsection 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#204]
Create a Index in top of the readme . Clicking in the title will take you to the section in readme .

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@KushalGhosh9899  Are you still working on it ?

**Comment by KushalGhosh9899** [comment]
@SaraswatGit I got busy with my exams. I'll try to complete it by tomorrow.
