### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by maityamit** [SaraswatGit/PlanZap#208]
Changes
Adding Issue templates
Template path  ``` .github/ISSUE_TEMPLATE ``` 
**Template Types**

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156574710-6e75dbde-7ee9-4cb7-9297-c516d5092eb8.png)
![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156574718-869a8c87-a672-4d4a-a32e-61e60fb0c6bc.png)

Contribution towards GSsoc`22, Thank you

**Comment by SaraswatGit** [comment]
@maityamit  Assigned , for any issues reach out to us on discord .

**Comment by maityamit** [comment]
@SaraswatGit
I think by mistake you assigned @Tess-Vanta . 


> @maityamit Assigned , for any issues reach out to us on discord .

**Comment by maityamit** [comment]
> @maityamit Assigned , for any issues reach out to us on discord .

Here you write 🥲 , @maityamit assigned but you assigned another ..

**Comment by Tess-Vanta** [comment]
> > @maityamit Assigned , for any issues reach out to us on discord .
> 
> Here you write 🥲 , @maityamit assigned but you assigned another ..

Might have been a mistake
