### ISSUE TITLE
Sidebar as separate component 

### ISSUE THREAD

**Issue by Deepak8717** [SaraswatGit/PlanZap#209]
I can separate the sidebar as seprate component for better readability

**Comment by SaraswatGit** [comment]
@Deepak8717  Assigned ,  @Tess-Vanta  Will be your mentor for the issue , for any problem reach out to us on discord .

**Comment by Deepak8717** [comment]
@SaraswatGit i don't have access to discord. I have even e-mailed you for that. It would nice if you could share discord link.

**Comment by Tess-Vanta** [comment]
> @SaraswatGit i don't have access to discord. I have even e-mailed you for that. It would nice if you could share discord link. Please note that i have been contributing but i am not part of Gssoc'22 group. I wondering if i would be allowed to contribute ?

YEs you can. Let us know if you are still interested

**Comment by jyotivakare33** [comment]
Can someone assign this issue to me willing to work on it under GSSOC'22

**Comment by Tess-Vanta** [comment]
Assigned! Feel free to contact us on discord for any type of clarification!!

**Comment by jyotivakare33** [comment]
@Tess-Vanta Thank you working on it

**Comment by Tess-Vanta** [comment]
> @Tess-Vanta Thank you working on it
> 

Are you working on this ?

**Comment by jyotivakare33** [comment]
Yes i have completed it will push it by 12 today @Tess-Vanta

**Comment by jyotivakare33** [comment]
https://github.com/SaraswatGit/PlanZap/pull/240 Please review @SaraswatGit @Tess-Vanta
