### ISSUE TITLE
Feature: Responsive Cards in Task And Progress Section

### ISSUE THREAD

**Issue by Shlok1999** [SaraswatGit/PlanZap#216]
### Feature description

Cards responsivity must be done better for mid sized screen view.
![Screenshot from 2022-03-10 21-11-38](https://user-images.githubusercontent.com/47269110/157698230-baebfbaa-3db5-4087-acd8-6bf070836eb3.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Shlok1999** [comment]
Please Assign me the issue @SaraswatGit

**Comment by SaraswatGit** [comment]
@Shlok1999  Assigned , @Tess-Vanta  will be your mentor for the issue ,  for any problem reach out to us on discord .

**Comment by Shlok1999** [comment]
@Tess-Vanta Please do suggest changes if required

**Comment by Tess-Vanta** [comment]
Its good! have merged your PR

**Comment by Tess-Vanta** [comment]
In full width the slider in the cards seems to overflow.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/72697074/157890063-89da5306-c5c1-4722-8471-bee23c514f14.png">
Make the changes and create a new PR.
