### ISSUE TITLE
Date Selection on Diary Page is not properly visible [Bug]: 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#221]
### Contact Details

no

### What happened?

Users' can't find a place to enter a date and thus make or update a siary entry . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Supriya2922** [comment]
Hey! Can I work on this issue.(GSSoc Contributor)

**Comment by SaraswatGit** [comment]
@Supriya2922  Assigned , @Alik-Kumar-Ghosh  Will be your mentor for the issue, for any problem reach out to us on discord .

**Comment by SaraswatGit** [comment]
@Supriya2922  May I get an update on your issue .

**Comment by Supriya2922** [comment]
Hey! Because of sem exams I couldnt work on it. I will make a PR by EOD.
