### ISSUE TITLE
Feature: Automatically add authors name and book description using api

### ISSUE THREAD

**Issue by mustali17** [SaraswatGit/PlanZap#223]
### Feature description

When the user enters the name of the book the authors name and book description will automatically fetched and added in the text field using an API.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by mustali17** [comment]
I want to work on this issue under GSSoC'22

**Comment by SaraswatGit** [comment]
@mustali17  The back-end of this page is ready yet , if done will let you know .

**Comment by SaraswatGit** [comment]
@mustali17  Assigned , for any problem reach out to us on discord .

**Comment by SaraswatGit** [comment]
@mustali17  May I  get an update on the issue .

**Comment by mayonk-kumar-git** [comment]
Hey, I am a contributor in GSSoC 22. I would like to work on this issue.

The API that we are talking about here is it already available in the backend folder? or do I need to create a custom API in the backend folder first? or can I use any online available API (if I can find one)

**Comment by SaraswatGit** [comment]
@mayonk-kumar-git Assigned , for any issues reach out to us on discord.
