### ISSUE TITLE
Back-end of Books page Feature: 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#224]
### Feature description

The books page does n't have a back-end yet create it on lines of the movies page . Please ping me on discord to move ahead with the issue . 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Shlok1999** [comment]
Please assign me this issue if availiable

**Comment by SaraswatGit** [comment]
@Shlok1999  someone else had request earlier on discord. If for some reason he is not able to do it , I will assign it to you .

**Comment by vakshit** [comment]
Please assign me the issue as discussed earlier on discord.
