### ISSUE TITLE
Active Navigation section is not visible on navbar when clicked . [Bug]: 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#230]
### Contact Details

saraswatmajumder@gmail.com

### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/58114914/158347608-a561d329-ccae-46b3-b64f-cd4fa315b7ae.png)
As you see in the pic when a certain route is active. It not visible on Navigation Panel . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arzitmahajan** [comment]
When this bug occur ?

**Comment by SaraswatGit** [comment]
@arzitmahajan  On clicking a navlink in the navigation panel u can look into the screenshot attached for more details .

**Comment by arzitmahajan** [comment]
I want to work on this please assign me
