### ISSUE TITLE
No Scroll Bar in Movies and Diaries page[Bug]: 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#236]
### Contact Details

saraswatmajumder@gmail.com

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sukriti-m** [comment]
Hi @SaraswatGit 
If this task is being delayed, then I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC'22.

**Comment by riyajaiswal25** [comment]
I wish to work on this.

**Comment by SaraswatGit** [comment]
@KushalGhosh9899  Are you still working on this ?

**Comment by KushalGhosh9899** [comment]
No, you can assign it to anyone else.

**Comment by SaraswatGit** [comment]
@riyajaiswal25  Assigned for any problems reach out to us on discord .
