### ISSUE TITLE
Feature: Adding color to dropdown box to add difficulty levels . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#237]
### Feature description

![image](https://user-images.githubusercontent.com/58114914/159735273-0a59c679-68d0-4c51-a206-44fd3df7c160.png)
Currently the options have white color you can add color based on color of the cards . 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Aayush987** [comment]
I would like to work on this issue.
