### ISSUE TITLE
[Bug]: The delete button in the booksToRead section not working properly

### ISSUE THREAD

**Issue by mayonk-kumar-git** [SaraswatGit/PlanZap#245]
### Contact Details

mayonk.kumar9@gmail.com

### What happened?

The delete button in the books to read section not working properly. On clicking the delete button the last book is deleted always instead of the book that is being clicked.

### Screenshot of the issue
![4](https://user-images.githubusercontent.com/54724381/160279917-812da1e2-3a0a-4029-be4f-271091f0946f.JPG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mayonk-kumar-git** [comment]
I would like to work on this issue

**Comment by SaraswatGit** [comment]
@mayonk-kumar-git  Assigned .
