### ISSUE TITLE
Add pop up to confirm deletion of notes and movie

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#25]
Checkout on how trying to delete a task gives out a pop-up to confirm it. To close the issue you have brought in the same feature to confirm deletion of Movie/Task. 
A message like "Are you sure you want to delete the movie from movielisr" or something similar would suffice .

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@03amir I have assigned the issue to you , for any problems reach out to me on discord.
