### ISSUE TITLE
[Bug]: Visibility of date picker in task page

### ISSUE THREAD

**Issue by Tess-Vanta** [SaraswatGit/PlanZap#250]
### Contact Details

tejaswimhtp@gmail.com

### What happened?

The date picker in the task section is not visible.
![image](https://user-images.githubusercontent.com/72697074/161420734-194b4450-21e8-49f8-bfea-10ef6e414a57.png)
![image](https://user-images.githubusercontent.com/72697074/161420740-e617a3c2-76b4-4bea-848b-48000d883814.png)
change the color of the date picker and make it visible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aayush987** [comment]
I can work on this issue. Plz assign it .

**Comment by Tess-Vanta** [comment]
Assigned! For any doubts reach us out on discord!!
