### ISSUE TITLE
Feature: A logo would make it attractive.

### ISSUE THREAD

**Issue by riyajaiswal25** [SaraswatGit/PlanZap#254]
### Feature description

A logo in the website would make it attractive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by SaraswatGit** [comment]
@riyajaiswal25  Where would the logo come up and what about the existing logo ?

**Comment by TG922** [comment]
is someone working on this issue??

**Comment by nik132-eng** [comment]
if this issue is still open I want to work on this issue. can you please assign me this issue? for GSSoC

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by SaraswatGit** [comment]
@SHRUTI-SINGH16  assigned
