### ISSUE TITLE
[Bug]:Sign in not working properly

### ISSUE THREAD

**Issue by piyusha2001** [SaraswatGit/PlanZap#257]
### Contact Details

ppiyusha2001@gmail.com

### What happened?

After logging out when we are signing in , It is signing us in without taking email and password input .

### Relevant log output

```shell
It should take input first and then sign in
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaraswatGit** [comment]
@piyusha2001  Assigned !!
