### ISSUE TITLE
Show a loading sign till the api has not fetch the entire movie-list , task-list or notes . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#26]
You must have encountered that when you go to the movie list page, notes page, or tasks page. The page shows a blank white screen before fetching the lists. To solve this issue you need to show a loading sign till the list has been fetched. 

You can look at how the app.js returns a loading page till it has got a response using the useState react hook.

Best of Luck

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@03amir  I have assigned the issue to you, Best  Wishes, for any problems reach out to me on discord.
