### ISSUE TITLE
Add a how to use section .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#27]
A section should come below the "Ideas and Notes" section explaining to new users how the website needs to be used.  Like how to add tasks, how to edit them, how to add a new note etc.

**Comment by ronitblenz** [comment]
Hi, I wanna work on this issue.

**Comment by SaraswatGit** [comment]
@ronitblenz  Under JWOC right ?

**Comment by ronitblenz** [comment]
> @ronitblenz Under JWOC right? I have assigned the issue to you, for any problem reach out to me on discord.

Yes JWoC . 
Thank you for assigning

**Comment by ronitblenz** [comment]
Hi, @SaraswatGit Can you Kindly unassign me from this issue
I am not equipped with React that much
And my semester is nearing, cant invest much time in it.
I really apologise for this, Thank you for supporting with all the materials and moral support. You were a great mentor✨.

**Comment by SaraswatGit** [comment]
@ronitblenz  It alright keep an eye on the project, maybe you can get an issue of your choice in the coming days.

**Comment by SaraswatGit** [comment]
@03amir  I have assigned the issue to you , Best Wishes for any problems reach out to me on discord.
