### ISSUE TITLE
Add a new feature to display the tasks based on user preference . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#28]
A button should come up beside the Add New Task clicking on which a pop showing all tasks will appear. Now there should be an option to  arrange the tasks in the following manner :

1)Based on deadline (a task with the earliest deadline should come at the top)

2)Based on % of work left (a task with most work left will come at the top)

3)Based on both (here you should or can use the fractional knapsack concept, you will arrange elements by the 
following formula: (% work left / No. of days left )* (3/2/1 for highest/medium/lowest priority) ,   the one with the highest value of the given formula will come at top)

You can refer to the following article  : https://stackoverflow.com/questions/5002848/how-to-define-custom-sort-function-in-javascript

**Comment by DarkFalc0n** [comment]
I would like to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@DarkFalc0n  I have assigned the issue to you, Best Wishes, for any problems reach out to me on discord.
