### ISSUE TITLE
Update Quote Pop - Up and  Update/Add DIary entry pop button is too large

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#29]
I think there are conflicts in CSS imports in the mentioned pop-ups. Try to resolve it.
The size of the add entry is too big
![image](https://user-images.githubusercontent.com/58114914/153185442-6fe956c7-83d9-4ebd-a740-023a5aba070e.png)

**Comment by Tess-Vanta** [comment]
I would like to take this up under JWOC

**Comment by Tess-Vanta** [comment]
> @Tess-Vanta  I have assigned the issue to you , Best wishes , for any problem reach out to me on discord .

I like your speed 😄
