### ISSUE TITLE
Improving the Login and Registration Features and UI .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#3]
- The UI of the login page has to be improved
- There should be a login window for registered users.
- There should be a registration pop-up for non-registered users. 
- After user has completed registration , display a message saying registration complete and a link to redirect to login page

**Comment by navyagarwal** [comment]
I would like to work on this issue under JWOC.

**Comment by SaraswatGit** [comment]
> I would like to work on this issue under JWOC.

I have assigned the issue to you best wishes for any doubts ping me on Discord!

**Comment by Rik-21** [comment]
Can i work on this issue under JWoC

**Comment by SaraswatGit** [comment]
@Rik-21  The issue has already been assigned please checkout other issues
