### ISSUE TITLE
Improving the UI of Deletion Confirm pop-up in Tasks , Movies and Ideas.

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#31]
The current deletion Pop-up needs to be enhanced. Do your best and attach a screenshot . Also change the message from are you sure to delete to Do you want to delete the task (for tasks ), movie (for movies )

![image](https://user-images.githubusercontent.com/58114914/152981695-79bc561a-c261-4cc8-8e95-866069e632dd.png)

**Comment by Tess-Vanta** [comment]
I would like to take up this issue under JWOC

**Comment by SaraswatGit** [comment]
@Tess-Vanta  I have assigned the issue to you , Best Wishes , for any problem reach out to me on discord .
