### ISSUE TITLE
Replace the delete in movies section with a trash can icon from MUI 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#36]
![image](https://user-images.githubusercontent.com/58114914/153274675-4a20c969-0c3a-4d87-b56b-0d19dc8a758a.png)
This should be replaces by an icon on trashcan from material UI and should be next to the edit icon .

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by SaraswatGit** [comment]
@Tess-Vanta  I have assigned the issue to you, Best Wishes, for any problem reach out to me on discord.
