### ISSUE TITLE
Enable auto-fill based on login section . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#38]
![image](https://user-images.githubusercontent.com/58114914/153360738-ac92fb9c-1bf5-4fc6-a2c3-9a1176a555c2.png)
On entering email generally, password shows up. But this is not happening here .

**Comment by Jyoti6828** [comment]
Can you please tell me for my clearance, what exactly this issue is?

**Comment by SaraswatGit** [comment]
@Jyoti6828  I have assigned the issue to you, Best Wishes,for any problem reach out to me on discord.

**Comment by SaraswatGit** [comment]
@riiyaaa    I have assigned the issue to you , Best Wishes , for any problems reach out to me on discord .

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by SaraswatGit** [comment]
@tanya-gupta25  I have assigned the issue to you , Best wishes for any issues reach out to me on discord .

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@DarkFalc0n  I have assigned the issue to you , Best Wishes for any problem reach out to me on discord  .

**Comment by Aniket-508** [comment]
I want to work on this under JWoC.

**Comment by SaraswatGit** [comment]
@Aniket-508  I have assigned the issue , to you Best Wishes , for any problem reach out to me on discord.

**Comment by SaraswatGit** [comment]
This seems fine I am merging it @Aniket-508
