### ISSUE TITLE
The last quote disappears if no change is made .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#4]
- If you have gone through the website you must have seen there is a quote section. Now when you try to edit, it just omits the last quote completely and take whatever is written in the box(Modal) it even disappears if no change is made. 
- You can go through the Notes and Movie list section which has edit features but they don't disappear like in here(quote section). 
- For better understand pleasing ping me on discord .

**Comment by bhaktikarangale0201** [comment]
I like to work on this issue.

**Comment by SaraswatGit** [comment]
@bhaktikarangale0201  I  have assigned the issue to you , Best Wishes , for any problems reach out to me on discord .

**Comment by 03amir** [comment]
I want to work on this issue under JWOC. As previous mentee has crossed the deadline.

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC.

**Comment by SaraswatGit** [comment]
@dhruvtongia  I have assigned the issue to you, Best Wishes, for any problem reach out to me on discord.
