### ISSUE TITLE
On Deleting  a task confetti should not pop up 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#44]
You must have observed a new confetti feature on our website. The thing is this appears even when a user deletes a task (clicking on a cross button) . To resolve this call the API call when user wants to delete and API call when user has completed the task should come inside different functions .

**Comment by Aniket-508** [comment]
@SaraswatGit I want to work on this issue under JWoC.

**Comment by SaraswatGit** [comment]
@Aniket-508  I have assigned the issue to you, Best Wishes, for any problem reach out to me on discord .
