### ISSUE TITLE
Deadline Date Selection for New Tasks

### ISSUE THREAD

**Issue by Aniket-508** [SaraswatGit/PlanZap#46]
Currently, the user is able to select previous dates than today which is not feasible. 
Solution proposed. The calendar should disable the selection of past dates than today and allow only selection of future dates.

**Comment by Aniket-508** [comment]
@SaraswatGit I want to work under this issue under JWoC.

**Comment by SaraswatGit** [comment]
@Aniket-508  I have assigned the issue, to you, Best Wishes.For any problems reach out to me on discord .

**Comment by Aniket-508** [comment]
@SaraswatGit Please assign medium to this because I have to write custom javascript and not just a single property or attribute?
