### ISSUE TITLE
Create a static page for when the site is under maintenance 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#47]
Create a State(underMaintenance, setUnderMaintainence) hook initially to set false in app.js which when true the App fill return that page  to the user

**Comment by Aniket-508** [comment]
@SaraswatGit I want to work on this issue under JWoC.

**Comment by SaraswatGit** [comment]
@Aniket-508  I have assigned the issue to you , Best Wishes for any problem reach out to me on discord
