### ISSUE TITLE
Dairy Date Selection while adding new note.

### ISSUE THREAD

**Issue by Aniket-508** [SaraswatGit/PlanZap#49]
Currently, the date selection is allowed for future dates as well which is not logical according to what diary is meant for. Solution proposed : The user will only be able to select date till today or past dates but not future ones.

**Comment by Aniket-508** [comment]
@SaraswatGit Please assign me this issue under JWoC.

**Comment by SaraswatGit** [comment]
@Aniket-508  I have assigned the issue to you , Best Wishes for any problem reach out to me on discord
