### ISSUE TITLE
Improving the documentation(README.md)

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#5]
The structure and understanding of the documentation can be improved . For example, diving it into sections like installing required apps to run the app on local machines. Telling about how the app is structured. Improve UI of the documentation.

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by Sanket1308** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
Can I work on this issue under JWoC?

**Comment by SaraswatGit** [comment]
@Srijita-Mandal  I have assigned the issues to you , best wishes , for any problems reach out to me on discord .
