### ISSUE TITLE
Improving the UI of the loading page 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#6]
The current loading page has a very poor UI this can be improved. I am open to suggestions

**Comment by Rohan-Hazari** [comment]
I want to work on this issue under JWOC

**Comment by PrajwalDhule** [comment]
hello, I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
> hello, I want to work on this issue under JWOC

Thanks @PrajwalDhule  but issue has already been assigned do look out for other issues!!

**Comment by SaraswatGit** [comment]
@PrajwalDhule  The previous assignee  has backed out , So I have assigned it to you , Best Wished for any doubts reach out to me on Discord .

**Comment by raxvab** [comment]
I want to work with this issue under JWOC

**Comment by SaraswatGit** [comment]
> I have assigned it to you , Best Wishes for any doubts reach out to me on Discord .

I have assigned it to you , Best Wishes for any doubts reach out to me on Discord .

**Comment by SaraswatGit** [comment]
> I want to work with this issue under JWOC

I have assigned it to you , Best Wishes for any doubts reach out to me on Discord .
