### ISSUE TITLE
Display a Pop - Up telling user to visit the How to use section to understand how to use the website . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#64]
You should use localStorage to check if the user has visited the website or not. 

On logging, in the first time, a pop-up should suggest the user to visit the how to use section a button in the popup "Go to How to use" should re-direct her to how to use section /

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@03amir  I have assign the issue to you , Best Wishes for any problem reach out to me on discord .
