### ISSUE TITLE
Check strength of the password entered by the user 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#65]
You can use Yup package for this .

**Comment by abhiimali** [comment]
i want to work on this issue under JWOC

**Comment by abhiimali** [comment]
i am new  to development and open source will give my best

**Comment by SaraswatGit** [comment]
@abhiimali  I have assigned the issue to you, Best Wishes for any problem reach out to me on discord.

**Comment by Devmindtk** [comment]
I want to work on this issue. please assign to me

**Comment by SaraswatGit** [comment]
@Devmindtk This issue has already been assigned in case the current assignee can't close it , I will assign it to you
