### ISSUE TITLE
The add new task , sort the tasks modal should be responsive when viewing the Site in landscape mode .  

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#66]
You must have observed the modal is not exactly responsive when viewing the site in landscape mode  . You need to fix it .

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@Shruti025  I have assigned the issue to you, Best Wishes, for any problem reach out to me on discord.

**Comment by Shruti025** [comment]
Sure, thanks!
