### ISSUE TITLE
Add a feature to sort movies based on their imdb . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#68]
A small triangular button should come near the IMDb header to sort the list based on the IMDb rating.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-508** [comment]
I want to work on this issue under JWoC.

**Comment by SaraswatGit** [comment]
I have assigned the issue to you , Best wishes , for any problem reach out to me on discord .
