### ISSUE TITLE
Feature to edit idea and description inline intead of opening a modal . 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#69]
On clicking the edit button in the test should become editable and a save button should appear.  This will replace the current usage of Modal to edit task names and description.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@03amir  I have assigned the issue to you , Best Wishes , for any problem reach out to me on discord.
