### ISSUE TITLE
fix: Warnings on VS code/ Console

### ISSUE THREAD

**Issue by KushalGhosh9899** [SaraswatGit/PlanZap#77]
While running the app by running the `npm start` command on the console then there is a number of warnings that are coming on the console.
These warnings will be resolved in this issue.

Snapshot of warning-
![image](https://user-images.githubusercontent.com/25982821/155028778-0e10d678-7eeb-4fd9-b2a1-4a9c7615c452.png)

**Comment by KushalGhosh9899** [comment]
This will be under JWOC if you feel this issue is valid.

**Comment by SaraswatGit** [comment]
@KushalGhosh9899  I have assigned the issue  to you , Best Wishes for any problem reach out to me on discord .
