### ISSUE TITLE
Remove the UI error on Login Page 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#78]
![image](https://user-images.githubusercontent.com/58114914/155045232-fa900d7d-174b-4533-aabd-84bf4255c3cd.png)
A blue line appears on the login page please fix it. It should not appear.

**Comment by Shruti025** [comment]
I want to work on  this under JWOC

**Comment by SaraswatGit** [comment]
@Shruti025  I have assigned the issue to you , Best Wishes,  for any problem reach out to me on Discord .
