### ISSUE TITLE
Login Page and Register Box Responsiveness

### ISSUE THREAD

**Issue by Shruti025** [SaraswatGit/PlanZap#80]
The Login Page and Register Box are not responsive

Screenshots:
![image](https://user-images.githubusercontent.com/72005584/155058196-472e28b9-59d0-4ab9-892a-eee3fe1a2b24.png)
![image](https://user-images.githubusercontent.com/72005584/155058277-970d2e57-4cc3-402b-a1aa-24d477f801f4.png)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by SaraswatGit** [comment]
@Shruti025  I have assigned the issue to you , Best Wishes for any problem reach out to me on discord .
