### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by biswajit150803** [SaraswatGit/PlanZap#89]
Needs changes in the designing of the website including navigation bar and styling

**Comment by biswajit150803** [comment]
I want to work on this issue under GSSoC 22

**Comment by SaraswatGit** [comment]
Can you elaborate more the issue you are trying to work upon @biswajit150803

**Comment by biswajit150803** [comment]
> Can you elaborate more the issue you are trying to work upon @biswajit150803

Actually I want to use a different navigation bar and also the form that clicks up while on clicking movies,tasks needs some changes in the layout
