### ISSUE TITLE
Switching to Landscape mode when width is less than 600 px (Media Query)

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#9]
You must have seen our website is not quite responsive, the thing is its design in a such a way it's not possible to make it one but what we can do here is just switch the entire app to landscape mode when the width is less than 600px 

You have to display a warning message this website is  viewable only in landscape mode and block the rest of the website.

**Comment by Tess-Vanta** [comment]
I want to work for this issue under JWOC

**Comment by SaraswatGit** [comment]
@Tess-Vanta  The issue has been assigned to you, Best Wishes, for any problem reach out to me on discord.

**Comment by Tess-Vanta** [comment]
Thanks!!
