### ISSUE TITLE
Create new files to contain Movie List ,Diary & notes.

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#90]
The current index.js in the Backend folder is becoming quite complex. So create new files (1 each more movie list , diary and notes)that will containers queries for Movie List, Diary and notes  .

**Comment by dakshgupta2002** [comment]
I want to work on this issue under JWOC

**Comment by SaraswatGit** [comment]
@dakshgupta2002 I have assigned the issue to you , Best Wishes for any problem reach out to me on discord .
