### ISSUE TITLE
Add code of conduct to the readme .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#91]
following should be added .
1) only npm to be used for managing packages.
2)only those libraries and packages which have >1000 downloads per weeks to be used . 
3)spamming issues may lead to banning user from contributing to the project. 
4)No disrespectful comments towards any gender , sex , caste , nationality will be tolerated .

**Comment by AviralSheoran** [comment]
Hello, I'm a GSSo'C 2022 Contributor,
Please assign me this issue, I want to add Code of Conduct to Readme

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by SaraswatGit** [comment]
@Shruti025  I have assigned the issue to you , Best Wishes , for any problem reach out to me on discord .
