### ISSUE TITLE
Add GSSOC logo and PR rules in the readme 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#92]
You have two sub-tasks :
1)Add a rule under the section explaining pull request in readme  to add screenshot or screen-recording when submitting a  PR. 
2)Add a GSSOC logo in the 2nd last section . (Part of these open source programs . )

**Comment by aaryahjolia** [comment]
Hii ! I'm a GSSoC'22 contributor. Can I work on this issue ?

**Comment by SaraswatGit** [comment]
@aaryahjolia  I have assigned the issue to you , Best Wishes for ant problem reach out to me on discord .

**Comment by Atharv-110** [comment]
Hey may you assign this issue to me please, I can work on this much effectively.

**Comment by SaraswatGit** [comment]
@Atharv-110  wait for few more hours if the current assigned is not able to close this I will assign it to you

**Comment by aaryahjolia** [comment]
I will merge a PR in sometime only.

**Comment by aaryahjolia** [comment]
@SaraswatGit It will be good for contributors if you close this issue.
