### ISSUE TITLE
On  registering redirect to calendar page

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#93]
Currently one redirects to calendar page only on logging in and on registering one needs to log in again to enter the website . 

Hint  : You can use async await or then() to resolve this issue . Once the user has been create , log in by calling the same API called for logging in the user proving it with email and password .

**Comment by dakshgupta2002** [comment]
I want to work on this under JWOC

**Comment by SaraswatGit** [comment]
@dakshgupta2002   I have assigned the issue to you , Best Wishes for any problem reach out to me on discord .
