### ISSUE TITLE
Improve UI of movie list page 

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#94]
![image](https://user-images.githubusercontent.com/58114914/156029460-25b6892d-4705-4b05-862d-7492a4225048.png)
The imdb column should be thinner as it will contain max 3 digits . The movie name and description should has more padding on left add 2X nbsp; or just increase the left padding .

**Comment by biswajit150803** [comment]
I want to work on this issue under GSSoC 22.Can you assign this to me?

**Comment by SaraswatGit** [comment]
@biswajit150803  I have assigned the issue to you , Best Wishes for any problems reach out to me on discord .

**Comment by biswajit150803** [comment]
> 

I am working on this issue but currently my semester exams are going on so I need some time

**Comment by SaraswatGit** [comment]
@biswajit150803  We are unassigning you.

**Comment by biswajit150803** [comment]
Sorry but can I know the reason behind this?

**Comment by SaraswatGit** [comment]
@biswajit150803  We didn't get any update on your progress are you still working on it ? If yes then we will assign u again

**Comment by biswajit150803** [comment]
Sir actually I had commented on this when i was asked about the update but I dont know I cant find the comment now.Actually sir I am working on this proj but the main prob is I am having my offline Semester exams till 10th March so thats why my working speed is a little slow.i hope u would understand my condition and assign this proj to me coz I have already started working on this project.

**Comment by SaraswatGit** [comment]
@biswajit150803  I am closing this issue , we can't wait any longer .
