### ISSUE TITLE
Improve lazy loading of images in How to use section .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#95]
The images load slowly causing bad UI experience for the user . Maybe display a circular loader till the images have loaded .

**Comment by unnikrishnan2002** [comment]
Can I try on this issue for GSSoC ?

**Comment by SaraswatGit** [comment]
@unnikrishnan2002  I have assigned the issue to you, Best wishes for any problem reach out to me on discord.
