### ISSUE TITLE
Diary View should be called on selecting a date .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#96]
Remove the View button in the diary section. The diary entry view api should be called on changing i.e selecting a date .

**Comment by Aayush987** [comment]
Plz assign it to me .I want to work on it.

**Comment by SaraswatGit** [comment]
@Aayush987 I have assigned the issue to you , Knowledge of Javascript and HTML is enough for this issue.

**Comment by Aayush987** [comment]
> @Aayush987 I have assigned the issue to you , Knowledge of Javascript and HTML is enough for this issue. 

Oh ok I know these things.I can do it.Thank you @SaraswatGit
