### ISSUE TITLE
Confetti celebration time should be reduced and transition should be smooth .

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#97]
Confetti celebration on clicking task done : Reduce the transition time by 50-70 percent and make the transition smoother

**Comment by Shikhar253** [comment]
Hey, I am a contributor in GSSOC 22, can you assign this issue to me?

**Comment by SaraswatGit** [comment]
@Shikhar253  I have assigned the issue to you , Best Wishes for any problem reach out to me on discord .
